export const foodTypeImages: { [key: string]: string } = {
  Meat: "/assets/meat.jpg",
  Мясо: "/assets/meat.jpg",
  "М'ясо": "/assets/meat.jpg",
  Dessert: "/assets/dessert.jpg",
  Десерт: "/assets/dessert.jpg",
  "Fast food": "/assets/fastfood.jpg",
  Фастфуд: "/assets/fastfood.jpg",
  "Soft drink": "/assets/drink.jpg",
  "Безалкогольний напій": "/assets/drink.jpg",
  "Безалкогольный напиток": "/assets/drink.jpg",
  "Alcohol drink": "/assets/alcohol.jpg",
  "Алкогольний напій": "/assets/alcohol.jpg",
  "Акогольный напиток": "/assets/alcohol.jpg",
  Soup: "/assets/soup.jpg",
  Суп: "/assets/soup.jpg",
  Porridge: "/assets/porridge.jpg",
  Каша: "/assets/porridge.jpg",
  Salad: "/assets/salad.jpg",
  Салат: "/assets/salad.jpg",
  "National dish": "/assets/national.jpg",
  "Національна страва": "/assets/national.jpg",
  "Нацыональное блюдо": "/assets/national.jpg",
  Pasta: "/assets/pasta.jpg",
  Макаронні: "/assets/pasta.jpg",
  Макаронные: "/assets/pasta.jpg",
  Fish: "/assets/fish.jpg",
  Рыба: "/assets/fish.jpg",
  Риба: "/assets/fish.jpg",
};
