import type { Metadata } from 'next'
import { Poppins }       from 'next/font/google'
import                        '../globals.css'
import Topbar            from '@/components/shared/Topbar'
import LeftSidebar       from '@/components/shared/LeftSidebar'
import Bottombar         from "@/components/shared/Bottombar";

const poppins = Poppins({ weight: ['400', '500', '700', '800'], subsets: ['latin'] })

export const metadata: Metadata = {
  title      : 'Recipebook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Topbar />
        <main className='flex flex-row'>
          <LeftSidebar />
          <section className='main-container'>
            <div className='w-full max-w-mw-1480 mt-28'>
              {children}
            </div>
          </section>
        </main>
        <Bottombar />
      </body>
    </html>
  )
}
